version: "3.8"
services:
  webledger-db:
    image: mysql:8.0
    container_name: webledger-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: webledger
      MYSQL_USER: webledger
      MYSQL_PASSWORD: webledgerpwd
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "3307:3306"
    volumes:
      - webledger_mysql_data:/var/lib/mysql

volumes:
  webledger_mysql_data:
